name: Update Card Names Catalog
on:
  schedule:
    - cron: 0 0 * * SUN
     # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-cards:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        persist-credentials: false
          
    - name: Fetch API Data 📦
      uses: JamesIves/fetch-api-data-action@releases/v2
      with:
        endpoint: https://api.scryfall.com/catalog/card-names
        configuration: '{ "method": "GET" }'
        save-location: assets
        save-name: test
        set-output: false
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: main # Pushes the updates to the main branch.
        folder: assets # The location of the data.json file saved by the Fetch API Data action.
        target-folder: assets # Saves the data into the 'data' directory on the main branch.
