name: Update Card Names Catalog V2
on:
  schedule:
    - cron: 0 0 * * SUN
     # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-cards:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Data to File
      uses: gautemo/fetch-api-data-action@1.1.0
      with:
         url: 'https://api.scryfall.com/catalog/card-names'
         file: 'assets/data.json'
