name: Update Standard Atomic Catalog
on:
  schedule:
    - cron: 0 0 * * MON
      # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-cards:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Fetch Data to File
        uses: gautemo/fetch-api-data-action@1.1.0
        with:
          url: 'https://mtgjson.com/api/v5/StandardAtomic.json'
          file: 'Test.json'

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # Pushes the updates to the gh-pages branch.
          folder: public # The location of the data.json file saved by the Fetch API Data action.
          target-folder: public # Saves the data into the 'data' directory on the main branch.
